spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_DB_HOST:localhost}:${LOCAL_DB_PORT:3306}/${LOCAL_DB_NAME:propit}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false