spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

openai:
  url: https://api.openai.com/v1/chat/completions

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2