#spring:
#  config:
#    import:
#      - optional:classpath:config.environments/common.yml
#      - optional:classpath:config.environments/${spring.profiles.active}.yml

server:
  port: 8080

# 자꾸 오류나서 내 로컬 디비 값 여기 그냥 써둠... 급하게 처리하느라 여기 써둔다.sorry 지워도 돼...

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/propit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: chaedbkey111!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false