server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      access-expire: ${JWT_ACCESS_EXPIRE}
      refresh-expire: ${JWT_REFRESH_EXPIRE}