spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

openai:
  api-key: ${OPENAI_API_KEY}
  url: https://api.openai.com/v1/chat/completions