spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false

security:
  jwt:
    token:
      secret-key: my-test-server-test-secret-key-12345678910
      access-expire: 3600000
      refresh-expire: 1209600000